<!DOCTYPE html>
<html lang="en">
<head>
    <!--Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--Libraries used by Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>

    <!--Font awesome CSS-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!--Bootstrap JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <!--Custom css-->
    <link rel="stylesheet" href="assets/css/custom-css.css">

    <!--Custom js-->
    <script src="assets/js/jquery-functions.js"></script>

    <title>Admin - Users listing</title>
</head>

<body>
<!--Header-->
<div class="d-flex flex-column flex-md-row align-items-center p-3 mb-3 bg-light border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Project name</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark">Hello, Admin <?php echo $username ?>!</span>
    </nav>
    <a class="btn btn-secondary" href="/">Logout</a>
</div>

<!--Breadcrumbs-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb px-3 py-0 mb-3">
        <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Users listing</li>
    </ol>
</nav>

<div class="container">
    <!--Page title block-->
    <div class="text-center">
        <h1>Users listing</h1>
    </div>

    <!--Table actions block-->
    <div class="row">
        <div class="col-12 col-md-2 d-flex align-items-center">
            <form action="">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <div class="btn-group" role="group">
                        <button name="role" id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <?php echo ($parameterBag->get('role') === '') ? 'All' : ucfirst($parameterBag->get('role')); ?>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                            <a class="dropdown-item" href="/admin-users-listing<?php echo $url->getUrl($parameterBag->all(),['role'=>'candidate']);?>">Candidate</a>
                            <a class="dropdown-item" href="/admin-users-listing<?php echo $url->getUrl($parameterBag->all(),['role'=>'admin']);?>">Admin</a>
                            <a class="dropdown-item" href="/admin-users-listing<?php echo $url->getUrl($parameterBag->all(),['role'=>'']);?>">All</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-12 col-md-6">
            <form method="GET" action="/admin-users-listing" >
                <?php foreach ($parameterBag->all() as $name => $value): ?>
                    <?php if ($value !== '' && $name !== 'email'): ?>
                        <?php  echo '<input type="hidden" name="' . $name . '" value="' . $value . '" />'; ?>
                    <?php endif;?>
                <?php endforeach; ?>
                <label for="textSearch">Email search</label>
                <div class="input-group">
                    <input name="email" type="text" id="textSearch" class="form-control" placeholder="" value="<?php echo $parameterBag->get('email');?>">
                    <div class="input-group-append">
                        <button class="btn btn-secondary" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="form-group col-12 col-md-2 d-flex align-items-end justify-content-end">
            <form method="GET" action="/admin-users-listing" >
                <?php foreach ($parameterBag->all() as $name => $value): ?>
                    <?php if ($value !== '' && $name !== 'results'): ?>
                        <?php  echo '<input type="hidden" name="' . $name . '" value="' . $value . '" />'; ?>
                    <?php endif;?>
                <?php endforeach; ?>
                <label for="results">Results Per. Page</label>
                <div class="input-group">
                    <input name="results" type="number" class="form-control" id="results" value="<?php echo $parameterBag->get('results');?>">
                    <div class="input-group-append">
                        <button class="btn btn-secondary" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-12 col-md-2 d-flex align-items-end justify-content-end">
            <a class="btn btn-primary py-1 mb-3" href="/admin-user-details/create">Add new user</a>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmDeleteLabel">Delete User</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this user ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger btn-ok">Delete</a>
                </div>
            </div>
        </div>
    </div>
    <!--Quiz listing table-->
    <div class="table-responsive my-4">
        <table class="table table-bordered">
            <thead>
            <tr>
                <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                <th scope="col" class="sorting-header <?php echo ($parameterBag->get('orderBy') == "id") ? (($parameterBag->get('sort') == "asc") ? "asc" : "dsc") : "asc dsc"; ?>"><a href="<?php echo $url->getUrl($parameterBag->all(),['orderBy'=>'id','sort'=>($parameterBag->get('sort') === "asc" ? "desc" : "asc")]);?>">ID</a></th>
                <th scope="col" class="sorting-header <?php echo ($parameterBag->get('orderBy') == "email") ? (($parameterBag->get('sort') == "asc") ? "asc" : "dsc") : "asc dsc"; ?>"><a href="<?php echo $url->getUrl($parameterBag->all(),['orderBy'=>'email','sort'=>($parameterBag->get('sort') === "asc" ? "desc" : "asc")]);?>">Email</a></th>
                <th scope="col">Name</th>
                <th scope="col">Role</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($users as $user): ?>
                <tr>
                    <td scope="row"><?php echo $user->getId(); ?></td>
                    <td><?php echo $user->getEmail(); ?></td>
                    <td><?php echo $user->getName(); ?></td>
                    <td><?php echo $user->getRole(); ?></td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="/admin-user-details/edit/<?php echo $user->getId(); ?>">Edit</a>
                        <a data-toggle="modal" data-target="#confirm-delete" class="btn btn-danger py-1" data-href="/admin-user-details/delete/<?php echo $user->getId(); ?>">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <!--Not sure if this is the best place for error messages-->
    <?php if ($messageManager->getErrorMessagesCount()): ?>
        <div class="alert alert-danger" role="alert">
            <?php echo implode('<br>',$messageManager->getErrorMessages());?>
        </div>
    <?php endif; ?>

    <!--Pagination block-->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item <?php if ($paginator->getCurrentPage() === 1) echo 'disabled'; ?>">
                <a class="page-link" href="<?php echo $url->getUrl($parameterBag->all()); echo $url->getUrl($parameterBag->all()) !== '' ? '&' : '?'; ?>page=<?php echo $paginator->getPreviousPage();?>" >Previous</a>
            </li>
            <?php for ($pageNumber = 1; $pageNumber <= $paginator->getTotalPages(); $pageNumber++): ?>
                <li class="page-item <?php if ($paginator->getCurrentPage() === $pageNumber) echo 'active'; ?>">
                    <a class="page-link" href="<?php echo $url->getUrl($parameterBag->all()); echo $url->getUrl($parameterBag->all()) !== '' ? '&' : '?'; ?>page=<?php echo $pageNumber;?>"><?php echo $pageNumber; ?></a>
                </li>
            <?php endfor; ?>
            <li class="page-item <?php if ($paginator->getCurrentPage() ===  $paginator->getTotalPages()) echo 'disabled'; ?>">
                <a class="page-link" href="<?php echo $url->getUrl($parameterBag->all()); echo $url->getUrl($parameterBag->all()) !== '' ? '&' : '?'; ?>page=<?php echo $paginator->getNextPage();?>">Next</a>
            </li>

        </ul>
    </nav>

</div>
</body>
</html>